[tool.poetry]
name = "drf-twitter"
version = "0.1.0"
description = ""
authors = ["yu"]
readme = "README.md"
packages = [{include = "mysite"}]

[tool.poetry.dependencies]
python = "^3.10"
flake8 = "^7.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
