# Generated by Django 4.2.9 on 2024-10-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appxxx", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
