name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Docker Compose
        run: |
          docker-compose up -d --build
          docker-compose exec drf pytest
        env:
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

      - name: Tear Down Docker Compose
        if: always()
        run: docker-compose down

  coverage:
    name: Coverage Report
    timeout-minutes: 10
    needs: test 
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Docker Compose for Coverage
        run: |
          docker-compose up -d --build
          docker-compose exec drf pytest --cov=src --cov-report=term-missing
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      
      - name: Tear Down Docker Compose
        if: always()
        run: docker-compose down

      - name: Check coverage
        run: |
          coverage_rate=$(docker-compose exec drf pytest --cov=src --cov-report=term-missing | grep TOTAL | awk '{print $4}' | sed 's/%//')
                        
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@v1.1.47
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml